from enum import Enum


class Meta(Enum):
    USER = "USER"
    PROJECT = "PROJECT"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
    REDIS_PASSWORD = "REDIS_PASSWORD"
    API_KEY = "API_KEY"
    PROJ_TOKEN = "PROJ_TOKEN"
    