from enum import Enum


class Meta(Enum):
    POSTGRES_USER = "POSTGRES_USER"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
    POSTGRES_DB = "POSTGRES_DB"
    REDIS_PASSWORD = "REDIS_PASSWORD"
    API_KEY = "API_KEY"
    PROJ_TOKEN = "PROJ_TOKEN"
    